### ISSUE TITLE
Release 1.5.0 - Alfajor

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#857]
### Required
- [x] #862 Handle empty hook file or other OSErrors
- [x] #834 Find the requested hook only
- [x] #850 pre_gen hook doesn't appear to be loading custom extensions
- [x] #856 Tests for custom extensions in hooks
- [x] #858 Use click to process dict variable
- [x] #861 Reproducible build with default config

### Optional
- [x] #791 add a jsonify filter to jinja default extensions
- [x] #849 Remove pycache directories in make clean-pyc
- [x] #855 Disable poyo logging for tests
- [x] #859 Extend CLI help message 

---

@audreyr @pydanny @michaeljoseph 🍪

**Comment by hackebrot** [comment]
🍪 @audreyr @pydanny @michaeljoseph 🍪

**Comment by hackebrot** [comment]
I can do the release, but I need a thumb from you ☺️

**Comment by michaeljoseph** [comment]
:+1: :+1:

**Comment by hackebrot** [comment]
👏 think we are ready to 🚀

**Comment by pydanny** [comment]
:+1:

**Comment by hackebrot** [comment]
@pydanny @michaeljoseph I'm getting a number errors when generating the long description for PyPI with restview. I vaguely remember that this was a problem last time as well, but I don't know how we solved it. Do we really need the full changelog on PyPI?

``$ restview --long-description --pypi-strict``

``Duplicate explicit target name: "cookiecutter-pyqt5".``

**Comment by hackebrot** [comment]
3379e99 does not look like this would resolve the errors I get now.

**Comment by hackebrot** [comment]
I propose to remove the changelog from the description, see #871

**Comment by hackebrot** [comment]
😂 https://github.com/audreyr/cookiecutter/releases/tag/1.5.0
